export const StatusContext = {
	"Water meter flow rate": {
		TYPE: "flow",
		SWITCH: false,
		MAX: 15,
		MIN: 0,
	},
	"Water heater temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 200,
		MIN: 0,
	},
	"Floor water sensor - bathroom 1": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Dry floor",
		RED: "Wet floor",
	},
	"Floor water sensor - bathroom 2": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Dry floor",
		RED: "Wet floor",
	},
	"Floor water sensor - bathroom 3": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Dry floor",
		RED: "Wet floor",
	},
	"Front door": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Door closed",
		RED: "Door open",
	},
	"Garage door": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Door closed",
		RED: "Door open",
	},
	"Side door": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Door closed",
		RED: "Door open",
	},
	"Family room window 1": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Family room window 2": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Bedroom 1": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Bedroom 2": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Bedroom 3": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Bathroom 1": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Bathroom 2": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window closed",
		RED: "Window open",
	},
	"Window breakage": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Window intact",
		RED: "Window broken",
	},
	"Motion sensor 1": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No motion detected",
		RED: "Motion detected",
	},
	"Motion sensor 2": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No motion detected",
		RED: "Motion detected",
	},
	"Motion sensor 3": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No motion detected",
		RED: "Motion detected",
	},
	"HVAC status": {
		TYPE: "boolean",
		SWITCH: false,
		GREEN: "HVAC on",
		RED: "HVAC off",
	},
	"HVAC blower": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Blower off",
		RED: "Blower on",
	},
	"HVAC mode": {
		TYPE: "modes",
		COUNT: 3,
		MODES: {
			HEAT: { COLOR: "RED", TEXT: "Heat mode" },
			COOL: { COLOR: "BLUE", TEXT: "Cool mode" },
			OFF: { COLOR: "GREEN", TEXT: "Off" },
		},
	},
	"Indoor temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 100,
		MIN: 40,
	},
	"Outdoor temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 120,
		MIN: -50,
	},
	"Refrigerator temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 50,
		MIN: -20,
	},
	"Ice maker filter": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Filter clean",
		RED: "Filter dirty",
	},
	"Freezer temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 50,
		MIN: -20,
	},
	"Stove status": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Stove off",
		RED: "Stove on",
	},
	"Dishwasher status": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Dishwasher off",
		RED: "Dishwasher on",
	},
	"Oven status": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "Oven off",
		RED: "Oven on",
	},
	"Upper oven temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 600,
		MIN: 0,
	},
	"Lower oven temperature": {
		TYPE: "temperature",
		SWITCH: false,
		MAX: 600,
		MIN: 0,
	},
	"Solar system status": {
		TYPE: "boolean",
		SWITCH: false,
		GREEN: "Online",
		RED: "Offline",
	},
	"Solar system fault": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No fault detected",
		RED: "Fault detected",
	},
	"Solar system production": {
		TYPE: "power",
		SWITCH: false,
		MAX: 40,
		MIN: 0,
	},
	"Utility power": {
		TYPE: "boolean",
		SWITCH: false,
		GREEN: "Providing power",
		RED: "Not providing power",
	},
	"Utility consumption": {
		TYPE: "power",
		SWITCH: false,
		MAX: 40,
		MIN: 0,
	},
	"Bedroom 1 smoke sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No smoke detected",
		RED: "Smoke detected",
	},
	"Bedroom 2 smoke sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No smoke detected",
		RED: "Smoke detected",
	},
	"Bedroom 3 smoke sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No smoke detected",
		RED: "Smoke detected",
	},
	"Master bedroom smoke sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No smoke detected",
		RED: "Smoke detected",
	},
	"Hallway smoke sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No smoke detected",
		RED: "Smoke detected",
	},
	"Garage heat sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No heat detected",
		RED: "Heat detected",
	},
	"Kitchen heat sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No heat detected",
		RED: "Heat detected",
	},
	"Carbon Monoxide sensor": {
		TYPE: "boolean",
		SWITCH: true,
		GREEN: "No CO detected",
		RED: "CO detected",
	},
};
